# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install ansible -y
  SHELL

  # vm1
  config.vm.define :master do |master|
    master.vm.hostname = "master"
    master.vm.network "public_network", ip: "172.26.17.114"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "MASTER"
    end
  end

  # vm2
  config.vm.define :dev do |dev|
    # dev.vm.box = "ubuntu/xenial64"
    dev.vm.hostname = "dev"
    dev.vm.network "public_network", ip: "172.26.17.115"
    dev.vm.provider "virtualbox" do |vb2|
      vb2.name = "DEV"
    end
    # dev.vm.provision :shell, inline: <<-SHELL
      # sudo apt update
    # SHELL
  end

  # vm3
  config.vm.define :prod do |prod|
    # prod.vm.box = "ubuntu/xenial64"
    prod.vm.hostname = "prod"
    prod.vm.network "public_network", ip: "172.26.17.116"
    prod.vm.provider "virtualbox" do |vb3|
      vb3.name = "PROD"
    end
    # prod.vm.provision :shell, inline: <<-SHELL
      # sudo apt update
    # SHELL
  end
end